/**
The lowest random number that can be generated by <code>randomRange</code> should be equal to your minimum number, <code>myMin</code>.
The highest random number that can be generated by <code>randomRange</code> should be equal to your maximum number, <code>myMax</code>.
The random number generated by <code>randomRange</code> should be an integer, not a decimal.
<code>randomRange</code> should use both <code>myMax</code> and <code>myMin</code>, and return a random number in your range.
*/