describe(`Lesson 104 generate random whole numbers within a range`, () =>{
	test(`The lowest random number that can be generated by <code>randomRange</code> should be equal to your minimum number, <code>myMin</code>.`, () =>{
		//test goes here
	})
	test(`The highest random number that can be generated by <code>randomRange</code> should be equal to your maximum number, <code>myMax</code>.`, () =>{
		//test goes here
	})
	test(`The random number generated by <code>randomRange</code> should be an integer, not a decimal.`, () =>{
		//test goes here
	})
	test(`<code>randomRange</code> should use both <code>myMax</code> and <code>myMin</code>, and return a random number in your range.`, () =>{
		//test goes here
	})
})